version: '3.9'
services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: citizenoffice
      POSTGRES_USER: citizen
      POSTGRES_PASSWORD: citizen
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"